name: docs

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - docs/**

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:
    posix:
        strategy:
            fail-fast: false

        name: Generate docs
        runs-on: ubuntu-22.04


        steps:
          - name: Checkout userver
            uses: actions/checkout@v3
            with:
                path: userver

          - name: Checkout doxygen
            uses: actions/checkout@v3
            with:
                repository: doxygen/doxygen
                path: doxygen

          - name: Checkout Docs Repository
            uses: actions/checkout@v3
            with:
                repository: alexiprof/userver-framework.github.io
                path: generated
                token: '${{ secrets.GH_USERVER_TECH }}'

          - name: Install packages
            run: |
                sudo apt install --allow-downgrades -y g++ cmake coreutils flex bison graphviz

          - name: Make doxygen
            run: |
                cd doxygen
                mkdir build
                cd build
                cmake -G "Unix Makefiles" ..
                make -j$(nproc)
                make install

          - name: Make docs
            run: |
                cd userver
                make opensource-docs

          - name: Copy docs
            run: |
                cd generated
                git rm -rf *
                cp -Ra -v ./../userver/docs/html/* ./

          - name: Git status
            run: |
                cd generated
                git add .
                git status

          - name: Git push
            run: |
                cd generated
                git config user.name github-actions
                git config user.email github-actions@github.com
                git commit -m "generated"
                git push
